### ISSUE TITLE
[f921038f] problem evaluating seeds

### ISSUE THREAD

**Issue by croth1** [soedinglab/BaMM_webserver#125]
Error in plotPvalStats.R

``` 
Error: Error: Some of the input p-values are missing!
Execution halted
Traceback (most recent call last):
  File "/ext/bin/shoot_peng.py", line 302, in <module>
    main()
  File "/ext/bin/shoot_peng.py", line 117, in main
    run_peng(args, output_directory, not args.no_scoring)
  File "/ext/bin/shoot_peng.py", line 208, in run_peng
    subprocess.run([RSCRIPT, os.path.abspath(output_directory), prefix], check=True, stdout=stdout)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
```

**Comment by croth1** [comment]
Strange error that's hard to reproduce - rerunning succeeds. Obtaining identically peng output, but all `.zoops.stats` files differ.

BUT: generation of `.zoops.stats` generally seems to be reproducible (identical between runs)

At this point there are few options:
 - race condition in `plotPvalStats.R`
 - super weird bug in memory/R?

Closing for now.

**Comment by WanwanGe** [comment]
The FDR function is currantly not deterministic yet.

**Comment by croth1** [comment]
latest version is now online.
