### ISSUE TITLE
[51e10f56] Error in if (strand_ind[i] == "+") { 

### ISSUE THREAD

**Issue by croth1** [soedinglab/BaMM_webserver#142]
```2019-08-11 09:13:31,153 [ERROR] misc: 'plotMotifDistribution.R' '/code/media/51e10f56-***/Output/' '<prefix>'
Traceback (most recent call last):
  File "/code/bammmotif/bamm/tasks.py", line 110, in denovo_pipeline
    generic_bammscan_task(job, first_in_pipeline=False, is_refined_model=True)
  File "/code/bammmotif/bammscan/tasks.py", line 33, in generic_bammscan_task
    BaMMScan(job, first_in_pipeline, is_refined_model)
  File "/code/bammmotif/bammscan/commands.py", line 82, in BaMMScan
    run_command(get_distribution_command(job))
  File "/code/bammmotif/utils/misc.py", line 107, in run_command
    raise CommandFailureException(command_str)
bammmotif.utils.misc.CommandFailureException: 'plotMotifDistribution.R' '/code/media/51e10f56-***/Output/' '<prefix>'
```

**Comment by croth1** [comment]
This was caused by `table.read` interpreting single quotes in fasta headers as quotation, leading to reduced number of lines read.
